### ISSUE TITLE
Convert Voting Screen UX to React Native with API Integration

### ISSUE THREAD

**Issue by aweb3dad** [The-Web3-Family/democracy-mobile-app#3]
## How to resolve
- The UX for the voting screen needs to be converted to react native: https://b_kxxtnnsfaub.v0.build/
- The UX needs to send data and retrieve data from the api endpoint https://my.api.mockaroo.com/bills.json?key=c83ad9c0

## Code that may assist you
https://v0.dev/chat/pQPD2SAeC0x
![image](https://github.com/user-attachments/assets/ad972ad7-7476-43af-9607-2ea88349faeb)

**Comment by milojeBtc** [comment]
The UI design on figma is better for me

**Comment by milojeBtc** [comment]
And in terms of api, if I can get swagger UI of it, that will be great for me

**Comment by milojeBtc** [comment]
The Codebase of it is already built a few days ago and now I am ready to work on UI as soon as design is ready

**Comment by aweb3dad** [comment]
Okay, however I don't have a figma for it, and that would require more resources to build that I do not have at the moment. I have that ai rendered code, and you ideally should be able to copy and paste a lot of the code that was generated from tailwind.

We'll focus on the ui later, but right now it's about integrated the ux. In which I'll update the issue right now to reflect that.

Considering that the issue itself here was ai generated, it may be incorrect, so I'll be making small edits till it makes sense. Updating now

**Comment by aweb3dad** [comment]
Updated to reflect the need of the issue to be resolved.

**Comment by aweb3dad** [comment]
I'll be providing the faux api endpoint later today. Feel free to ask any more questions. You're shaping right now how I will be communicating in every issue to you and others, so the more questions I have the better I can communicate.

Thanks in advance

**Comment by milojeBtc** [comment]
Okay, noted

**Comment by milojeBtc** [comment]
If you have HTML design for our app, that is also great for me. Just let me now what you think and then I will implement that into React Native

**Comment by milojeBtc** [comment]
In terms of api, I need brief introduction of each api so that is why I need a swagger UI for api.
And I need to consider all DB design to consider and make the request for server

**Comment by milojeBtc** [comment]
Sharing the backend code with me is great for me to understand all logic and workflow without any details explanation about the backend part

**Comment by aweb3dad** [comment]
@GideonMoses11 and I are still building the database model here:
https://github.com/The-Web3-Family/democracy-mobile-app-backend/issues/1

Are you asking for the models that will come back from the api?

Also maybe this will help, as all the tailwind classes are set here:
- Sample app: https://v0.dev/chat/pQPD2SAeC0x
- Published version of the sample: https://b_kxxtnnsfaub.v0.build/

You should be able to just copy and paste and then convert the code here into using react native components.

Let me know if you have any more questions... this is very good that you're asking all this, as I'm realizing I should probably post screenshots as well when it comes to ux conversion requests
![image](https://github.com/user-attachments/assets/51fb2f7f-1894-454c-be13-1a5aacc2e4fb)

**Comment by milojeBtc** [comment]
I have some question about the api.
![image](https://github.com/user-attachments/assets/88248cdb-0149-4673-8cf5-b6a5355743db)

This is the response from api.
Could you make me clear which field is match on which section on UI?

And also need a correct answer about the voting result.
